name: GitHub Action Test
run-name: Test
on: [push]
jobs:
    run-ruff:
        runs-on: ubuntu-latest
        steps:
            -   name: check out code
                uses: actions/checkout@v4

            -   name: Run ruff action
                uses: ./actions/ruff_action
                with:
                    project_path: "tests/ruff_project"
                    ruff_version: 'latest'
