name: GitHub Action Test
run-name: Test
on: [push]
jobs:
    Test:
        runs-on: 3.12.6-alpine3.20
        steps:
            -   run: |
                    python --version
                    python -m venv venv --upgrade-deps || python -m venv venv
                    source venv/bin/activate
                    pip install ruff
            -   run: |
                    cd tests/ruff_project/src/ruff_project
                    ruff check
                    ruff format