name: GitHub Action Test
run-name: Test
on: [push]
jobs:
    run-ruff:
        runs-on: ubuntu-latest
        container:
            image: python:3.12.6-alpine3.20
        steps:
            -   name: Run ruff action
                uses: ./.github/actions/ruff_action
                with:
                    project_path: "tests/ruff_project"
                    ruff_version: 'latest'
