on:
    workflow_call:
        inputs:
            project_path:
                description: 'Project to lint'
                required: false
                default: '.'
                type: string

jobs:
    ruff:
        runs-on: ubuntu-latest
        env:
            PROJECT_PATH: ${{ inputs.project_path }}
            RUFF_VERSION: 'latest'
            RUFF_CHECK_OPTIONS: ''
            RUFF_FORMAT_OPTIONS: '--check'
        container:
            image: kbauchswe/ruff:$RUFF_VERSION
            options: --user root

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run Ruff Linter
              run: |
                  ruff check $RUFF_CHECK_OPTIONS $PROJECT_PATH
                  ruff format $RUFF_FORMAT_OPTIONS $PROJECT_PATH
